// ============================================================
// ViberQC — Report Email Delivery (Resend)
// ============================================================

import { Resend } from "resend";

const FROM_EMAIL = process.env.FROM_EMAIL ?? "reports@viberqc.com";

function getResendClient(): Resend {
  const key = process.env.RESEND_API_KEY;
  if (!key) throw new Error("RESEND_API_KEY is not set");
  return new Resend(key);
}

export async function emailReport(
  to: string,
  pdfBuffer: Buffer,
  scanInfo: {
    url: string;
    score: number;
    scannedAt: string;
  },
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    const scanDate = new Date(scanInfo.scannedAt).toLocaleDateString("th-TH", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });

    const resend = getResendClient();
    const { data, error } = await resend.emails.send({
      from: `ViberQC Reports <${FROM_EMAIL}>`,
      to,
      subject: `QC Report: ${scanInfo.url} — Score ${scanInfo.score}/100`,
      html: `
        <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;">
          <div style="text-align:center;padding:20px 0;border-bottom:2px solid #6C63FF;">
            <h1 style="color:#6C63FF;margin:0;">ViberQC Report</h1>
          </div>

          <div style="padding:24px 0;">
            <p>สวัสดีครับ/ค่ะ,</p>
            <p>รายงาน QC Scan สำหรับ <strong>${scanInfo.url}</strong> พร้อมแล้ว</p>

            <div style="background:#F9FAFB;border-radius:8px;padding:20px;margin:20px 0;text-align:center;">
              <div style="font-size:48px;font-weight:bold;color:#6C63FF;">${scanInfo.score}/100</div>
              <div style="color:#6B7280;margin-top:4px;">Overall Score</div>
            </div>

            <table style="width:100%;border-collapse:collapse;">
              <tr>
                <td style="padding:8px 0;color:#6B7280;">URL</td>
                <td style="padding:8px 0;font-weight:bold;">${scanInfo.url}</td>
              </tr>
              <tr>
                <td style="padding:8px 0;color:#6B7280;">Scan Date</td>
                <td style="padding:8px 0;">${scanDate}</td>
              </tr>
            </table>

            <p style="margin-top:20px;">รายงานฉบับเต็มแนบมาในไฟล์ PDF</p>
          </div>

          <div style="text-align:center;padding:20px 0;border-top:1px solid #E5E7EB;color:#9CA3AF;font-size:12px;">
            Generated by ViberQC — AI-Powered 360° QC Platform
          </div>
        </div>
      `,
      attachments: [
        {
          filename: `viberqc-report-${Date.now()}.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, messageId: data?.id };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return { success: false, error: message };
  }
}
